### ISSUE TITLE
FR: Add Gmessages Bridge

### ISSUE THREAD

**Issue by kubo6472** [beeper/bridge-deployer#1]
Please add ability to deploy Google Messages bridge. The Android SMS use was discouraged by Beeper support last time I asked and the need to self host that bridge for now being the only option to have SMS in Beeper would make this project an important part of deploying it. I host a few stuff on fly.io.

**Comment by kubo6472** [comment]
Wanted to join in, realized neither https://hub.docker.com/layers/griffinli/bridge-manager/latest/images/sha256-c3f8dc4153561f83f155f819209339816be203d0098357fe9794182eec68d274?context=explore
nor https://hub.docker.com/layers/griffinli/bridge-manager-whatsapp/latest/images/sha256-1ecb81a4822b49368b7594966b7be478a2fa3a79d28f13b3809342cadd90f09e?context=explore
have a public Dockerfile to be found anywhere. If you are able to provide it somewhere, I'll be glad to start trying with gmessages @griffinli

**Comment by griffinli** [comment]
Hey - the Dockerfile is at https://github.com/beeper/bridge-manager/blob/fly/Dockerfile

Any contributions are welcome, but also know that you'll continue to have SMS access within Beeper without needing to self-host (you currently can still use the SMS bridge, and then can later switch over to a Beeper-hosted gmessages bridge once that feature is released for everyone).

**Comment by kubo6472** [comment]
![Screenshot_20230813-232200_Beeper](https://github.com/beeper/bridge-deployer/assets/26146502/93a5f10e-972c-415b-aebc-a0d9e61279be)

I have no problem self hosting. Will try to do something towards getting Google Messages into this. I'm in UTC+2 now, so will get into this in the morning.

**Comment by griffinli** [comment]
Sure - best of luck, feel free to ping with questions.

**Comment by kubo6472** [comment]
Your clever design made it very easy to make this work. Thanks for that.
